### ISSUE TITLE
Change in available emotions

### ISSUE THREAD

**Issue by anntr** [autyzm-pg/friendly-emotions#1]
# ENG:
# PL:
### stan obecny

W aplikacji możliwa jest nauka 5 emocji: 
- radość
- smutek
- złość 
- strach 
- zmęczenie 
### stan oczekiwany

W aplikacji należy dodać możliwośc nauki emocji: 
-  zdziwienie

**Comment by joagi** [comment]
Uczone emocje:
- wesoły
- smutny
- zdziwiony
- zły 
- przestraszony
- znudzony
