### ISSUE TITLE
Add ability to modify 'success' scene after excercise 

### ISSUE THREAD

**Issue by anntr** [autyzm-pg/friendly-emotions#3]
# EN
# PL
### stan obecny

Po poprawnie udzielonej odpowiedzi na zadanie, w celu uatrakcyjnienia dzieciom aplikacji, dodano ekran na którym wyświetlana jest udzielona odpowiedź, odtwarzany jest dźwięk a także animowane baloniki. 
### stan oczekiwany

Animacja powinna być elementem konfigurowalnym w panelu administracyjnym - dodać możliwość wyboru animacji spośród wielu, np. samochód, motyl, żabka. 
Uatrakcyjnić animację poprzez dodanie interakcji z nią. 
Przykładowo: 
- po dotknięciu samochodu, samochod przyspiesza / mruga światłami. 
- Motylek po dotknięciu porusza skrzydłami / zmienia tor ruchu.

**Comment by joagi** [comment]
Animacja jest elementem konfigurowalnym w panelu terapeuty.
Interakcja do zrobienia w przyszłych wersjach aplikacji
